<table class="plainForm">
  <tr>
    <th>Label</th>
    <td><html:text property="label" size="80"/></td>
  </tr>

  <tr>
    <th>Notes</th>
    <td><html:textarea property="notes" cols="60" rows="10"/></td>
  </tr>

  <tr>
    <td colspan="2" class="buttons">
      <html:hidden property="albumId"/>

      <html:submit>Ok</html:submit>
      <html:cancel>Cancel</html:cancel>
    </td>
  </tr>
</table>

